#!/usr/bin/env python3

#Full deploy on two different regions with route53 failover

import subprocess
import sys

arguments = ""
#check that we have an args
if sys.argv[1] == "create":
  try:
    i = sys.argv.index("-e")
    profile_length = i
  except ValueError:
    profile_length = len(sys.argv)
    i = -1
    print("No arguments present, continuing")

  for profile in sys.argv[2:profile_length]:
    if i >= 0:
      arguments = " "+" ".join(sys.argv[i:len(sys.argv)])
    cmd = "AWS_DEFAULT_PROFILE="+profile +" ansible-playbook -i hosts full_deploy.yml" + arguments
    print(cmd)
    cmd_run = subprocess.run(cmd, capture_output=True, shell=True, check=True)
    if cmd_run.returncode != 0:
      print(cmd_run.stderr)
      break
    if cmd_run.returncode == 0 and i == -1 and len(sys.argv) > 3:
      cmd_route = "AWS_DEFAULT_PROFILE="+sys.argv[2]+ " AWS_SECOND_PROFILE="+sys.argv[3]+ " ansible-playbook -i hosts deploy_to_route53.yml"
      cmd_run_route = subprocess.run(cmd_route, capture_output=True, shell=True, check=True)
      if cmd_run_route.returncode != 0:
        print(cmd_run_route.stderr)
      if cmd_run_route.returncode == 0:
        print("Successfully deployed the full-deploy playbook for profile: " + profile)
    elif cmd_run.returncode ==0:
        print("Successfully deployed the full-deploy playbook for profile: " + profile)

  #running the deploy to route53 again with two regions 
if sys.argv[1] == "route" and len(sys.argv) > 3:
  cmd_route = "AWS_DEFAULT_PROFILE="+sys.argv[2]+ " AWS_SECOND_PROFILE="+sys.argv[3]+ " ansible-playbook -i hosts deploy_to_route53.yml"
  print(cmd_route)
  cmd_run_route = subprocess.run(cmd_route, capture_output=True, shell=True, check=True)
  if cmd_run_route.returncode != 0:
    print(cmd_run_route.stderr)
  if cmd_run_route.returncode == 0:
    print("Successfully deployed the route53 for both regions on profile: " + sys.argv[2] + " and profile: "+ sys.argv[3])

if sys.argv[1] == "delete":
  try:
    i = sys.argv.index("-e")
    profile_length = i
  except ValueError:
    profile_length = len(sys.argv)
    i = -1
    print("No arguments present, continuing")

  for profile in sys.argv[2:profile_length]:
    cmd = "AWS_DEFAULT_PROFILE="+profile +" ansible-playbook -i hosts aws_cleanup.yml"
    print(cmd)
    cmd_run = subprocess.run(cmd, capture_output=True, shell=True, check=True)
    if cmd_run.returncode != 0:
      print(cmd_run.stderr)
      break
    if cmd_run.returncode == 0:
      print("Successfully deleted the infrastructure for profile: " + profile)
