#!/usr/bin/env python3

#Full deploy on two different regions with route53 failover

import subprocess
import sys

#check that we have an args
if sys.argv[1] == "create":
  for profile in sys.argv[2:]:
    cmd = "AWS_DEFAULT_PROFILE="+profile +" ansible-playbook -i hosts full_deploy.yml"
    cmd_run = subprocess.run(cmd, capture_output=True, shell=True, check=True)
    if cmd_run.returncode != 0:
      print(cmd_run.stderr)
      break
    if cmd_run.returncode == 0:
      print("Successfully deployed the full-deploy playbook for profile: " + profile)

  #running the deploy to route53 again with two regions 
  if len(sys.argv) > 2:
    cmd_route = "AWS_DEFAULT_PROFILE="+sys.argv[2]+ " AWS_SECOND_PROFILE="+sys.argv[3]+ " ansible-playbook -i hosts deploy_to_route53.yml"
    cmd_run_route = subprocess.run(cmd_route, capture_output=True, shell=True, check=True)
    if cmd_run_route.returncode != 0:
      print(cmd_run_route.stderr)
    if cmd_run_route.returncode == 0:
      print("Successfully deployed the route53 for both regions on profile: " + sys.argv[2] + " and profile: "+ sys.argv[3])

if sys.argv[1] == "delete":
  for profile in sys.argv[2:]:
    cmd = "AWS_DEFAULT_PROFILE="+profile +" ansible-playbook -i hosts aws_cleanup.yml"
    cmd_run = subprocess.run(cmd, capture_output=True, shell=True, check=True)
    if cmd_run.returncode != 0:
      print(cmd_run.stderr)
      break
    if cmd_run.returncode == 0:
      print("Successfully deleted the infrastructure for profile: " + profile)

if sys.argv[1] != "delete" or sys.argv[1] != "create":
    print("You have to specify create or delete a profile e.g auto_deploy create " +sys.argv[1])
