#!/usr/bin/env python3

#Full deploy on two different regions with route53 failover

import subprocess
import sys

#check that we have an args
if sys.argv[1:3]:
  for profile in sys.argv[1:3]:
    cmd = "AWS_DEFAULT_PROFILE="+profile +" ansible-playbook -i hosts full_deploy.yml"
    cmd_run = subprocess.run(cmd, capture_output=True, shell=True, check=True)
    if cmd_run.returncode != 0:
      print(cmd_run.stderr)
      break

  #running the deploy to route53 again with two regions 
  cmd_route = "AWS_DEFAULT_PROFILE="+sys.argv[1]+ " AWS_SECOND_PROFILE="+sys.argv[2]+ " ansible-playbook -i hosts deploy_to_route53.yml"
  cmd_run_route = subprocess.run(cmd_route, capture_output=True, shell=True, check=True)
  if cmd_run_route.returncode != 0:
    print(cmd_run.stderr)
  if cmd_run.returncode == 0: #and cmd_run_route == 0:
    print("Successfully deployed the full-deploy playbook for profile: " + sys.argv[1] + " and profile: "+ sys.argv[2])
  